name: "GitHub Issues to Azure DevOps as User Stories"
description: "This action will sync GitHub Issues to Azure Boards based on their assigned label. Only issues with the configured label will be taken into account."
author: "danhellem (Toolbastler)"
branding:
  icon: "book-open"
  color: "orange"
outputs:
  id:
    description: "id of work item created"
runs:
  using: "node12"
  main: "index.js"  
