name: GitHub Issues to Azure DevOps as User Stories

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:      
      - name: Test
        run: |
          echo $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          cat $GITHUB_EVENT_PATH >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0        
      - uses:  Toolbastler/github-actions-issue-to-user-story@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "Landaumedia"
          ado_project: "AllesWirdEins"
          ado_area_path: ""
          ado_iteration_path: ""                    
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          # define the list of label/tags of the issue to be processed
          # github_labels_whitelist: [ "User Story", "US", "Story" ]
          github_labels_whitelist: "User Story, Support Story"
          # for debugging purpose
          log_level: 100
